apiVersion: v1
kind: Service
metadata:
  name: devops-platform-service
spec:
  type: NodePort
  selector:
    app: devops-platform
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30080
